### ISSUE TITLE
bug in ordered simd test

### ISSUE THREAD

**Issue by naromero77intel** [TApplencourt/OvO#29]
Hello everyone,

I believe this test has a minor bug:
```
OvO/test_src/fortran/hierarchical_parallelism/ordered-real/target__parallel_do_simd.F90
```
(tier 2 test).

In particular,
```
  DO i0 = 1, N0
    !$OMP ordered simd
    counter_N0 = counter_N0 + 1.
    !$OMP end ordered **simd**
  END DO
```

The OpenMP 5.1 spec does _not_ allow any clauses hanging off the `end ordered`. It is a syntax error to have the **simd** on the end. OpenMP 5.1 Section 2.19.9.

Thanks for taking a look at this!

**Comment by TApplencourt** [comment]
The more I do OpenMP, the more I hate it :D 
Nice find, I will fix it :)!
