### ISSUE TITLE
Python 3.10.6 bug with tabulate_local.py.

### ISSUE THREAD

**Issue by estewart08** [TApplencourt/OvO#31]
I ran into this on Ubuntu 22.04 where python 3.10.6 is used. There is incorrect python version checking in tabulate_local.py, which causes errors when using python 3.10.
```
./ovo.sh report --summary
ModuleNotFoundError: No module named 'tabulate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/git/aomp-test/OvO/./src/report.py", line 14, in <module>
    from tabulate_local import tabulate
  File "~/git/aomp-test/OvO/src/tabulate_local.py", line 37, in <module>
    from collections import Iterable
```

More details here:
https://github.com/astanin/python-tabulate/issues/104

There was a patch to tabulate.py, which needs applied to your local version:
https://github.com/astanin/python-tabulate/pull/105/files

**Comment by TApplencourt** [comment]
Thanks a lot! Long time I didn't update this package :)

**Comment by ye-luo** [comment]
With #32 patch now I'm getting the above error on JLSE.

**Comment by TApplencourt** [comment]
I don't know how to make all people happy then...

The copy-pasted  `tabulate` version was just to avoid people doing a `pip install --local tabulate` or something like that.  :(

**Comment by estewart08** [comment]
Yes, no issue with Python 3.10.6.
