### ISSUE TITLE
Not clear about the function almost_equal()

### ISSUE THREAD

**Issue by juntaoma-intel** [TApplencourt/OvO#9]
Many tests use the same function almost_equal(), but when I ran some tests, it seemed that there was some misunderstanding about the function. 
eg: test_src/cpp/hierarchical_parallelism/atomic-float/target__parallel__for.cpp
```
#include <iostream>
#include <cstdlib>
#include <cmath>
bool almost_equal(float x, float gold, float tol) {
  return gold * (1-tol) <= x && x <= gold * (1 + tol);
}
void test_target__parallel__for() {
  const int N0 { 32768 };
  const float expected_value { N0 };
  float counter_N0{};
  #pragma omp target map(tofrom: counter_N0)
  #pragma omp parallel
  #pragma omp for
  for (int i0 = 0 ; i0 < N0 ; i0++ )
  {
    #pragma omp atomic update
    counter_N0 = counter_N0 + 1. ;
  }
  if (!almost_equal(counter_N0, expected_value, 0.1)) {
    std::cerr << "Expected: " << expected_value << " Got: " << counter_N0 << std::endl;
    std::exit(112);
  }
}
int main()
{
    test_target__parallel__for();
}
```
The function call during running is: 
line 40 in test_target__parallel__for(): almost_equal(32768., 32768, 0.1)
line 26 in almost_equal(): return 32768.*0.9 <= 32768 && 32768 <= 32768.*1.1;

The actual comparison is: 
    return 29491.2 <= 32768 && 32768 <= 36044.8;

But the comparison I understand should be:
    return 32767.9 <= 32768 && 32768 <= 32768.1;

Is there an error in my understanding of the program?

**Comment by colleeneb** [comment]
almost_equal is a function which says "return true if `x` is within `tol*100`% of `gold`". In this case it's if `x` is within 10% of gold, so if it's greater than `gold*0.9` and less than `gold*1.1`. Based on the numbers you used, it looks like you were thinking it was `gold-tol` and `gold+tol`, not `gold*tol`. 

So you are right that in this case it returns `return 32768.*0.9 <= 32768 && 32768 <= 32768.*1.1;`. If you carry out the multiplication you get `32768.*0.9=29491.2` and `32768.*1.1=36044.8`, just like the program shows. 


`

**Comment by TApplencourt** [comment]
Yes, It's  `almost_equal` use a `relative` tolerance and not an `absolute` one. I guess I should have named `tol` `rel_tol`.  PR are welcome to fix it :) 

If you want to have more information about how to compare numbers, this Python PEP (https://docs.python.org/3/library/math.html#math.isclose and https://www.python.org/dev/peps/pep-0485/) is useful.

**Comment by Ma-Steed** [comment]
My understanding is that for this test, counter_N0 and expected_value should be equal. Just considering the comparison of float and int, the almost_equal function is introduced.
But in this test, is the allowable error range of this test too large?  Here is the result ‘Expected: 32768 Got: 32761.6’ from a similar test.
According to the logic that I understand, the result of the test should be failed, but according to the error range of 10%, the result of the test is pass.
Will this hide some problems?

**Comment by TApplencourt** [comment]
You are totally right! I choose 10% totally arbitrary because I don't know any formula that can give an upper bound to the floating-point errors. 

If indeed we see  `Here is the result ‘Expected: 32768 Got: 32761.6`, and we are sure that it's due to a bug and not a floating-point issue, It will be better to lower the tolerance to 5% for example. 

Sadly, I don't know how to confirm that it's due to a bug... and not floating-point arithmetic. I will ask some people

**Comment by juntaoma-intel** [comment]
Would it be better to use the 'almost_equal' method of 'https://github.com/TApplencourt/OvO/blob/master/test_src/cpp/mathematical_function/cpp11/atan2_double_double_double.cpp' uniformly?

`bool almost_equal(double x, double y, int ulp) {
     return std::fabs(x-y) <= std::numeric_limits<double>::epsilon() * std::fabs(x+y) * ulp ||  std::fabs(x-y) < std::numeric_limits<double>::min();
}`

I can reproduce this issue when testing on host using IFX. Repeat the test with the 'fortran/hierarchical_parallelism/atomic-real-intermediate_result/target__teams__distribute__parallel__simd.F90' generated by 'ovo.sh gen tiers 2' and find that the part of pass is not really equal.
`bash-4.4# for i in {1..10};do ./target__teams__distribute__parallel__simd.exe;echo Times $i ret: $? ;done
 Expected       33124 Got   37387.00
112
Times 1 ret: 112
 Expected       33124 Got   37281.00
112
Times 2 ret: 112
 Expected       33124 Got   35921.00
Times 3 ret: 0
 Expected       33124 Got   36045.00
Times 4 ret: 0
 Expected       33124 Got   35627.00
Times 5 ret: 0
 Expected       33124 Got   37074.00
112
Times 6 ret: 112
 Expected       33124 Got   34589.00
Times 7 ret: 0
 Expected       33124 Got   34627.00
Times 8 ret: 0
 Expected       33124 Got   36868.00
112
Times 9 ret: 112
 Expected       33124 Got   35281.00
Times 10 ret: 0
`

**Comment by TApplencourt** [comment]
You are right. The current behavior is bad. 

I will switch to a more robust version where it will check for both relative and absolute tolerance. This should fix those problems. 10% seems true too large. We can do 5% or 10ULP. 

The fundamental problem is that I have no idea what tolerance should be. Do you have any recommendations? The atomic are performed in random order, hence the result at the end will fluctuate due to the floating point arithmetic. The question is how much is acceptable. 

Talking to people, the gold standard seems to be to take an arbitrary tolerance as stick with it... We can do 5% or 10ULP (if both failed the test fail). Do you think it will work for you?

**Comment by TApplencourt** [comment]
Ok, I fixed it in with 18773cecb9e5192c31139cb467d51ab7afed72ba  Can you pull, and try again?

**Comment by TApplencourt** [comment]
Let's said that fixed it :). Please reopen if that was not the case. 
I wrote this [page](https://github.com/TApplencourt/OvO/blob/master/documentation/FP_error.md) to explain the new reasoning.

Thanks again for opening the issue, it was indeed a bug so thanks :)

**Comment by TApplencourt** [comment]
Closed due to inactivity
